### PR TITLE
Enabled tests for tsv scripts.

### PR DESCRIPTION
**Pull request by dilawar**
Enabled tests in `TestTsv` folder.

### CODE REVIEW

**Comment by dilawar** [comment]
A single tsv file was failing with python2 but not with python3. Changes have been made to matplotlib related code to make sure that this passes with warning.

```
Warning: displayPlot: Failed to plot ./TestTSV/dr_ratio_b2c.tsv due to "Data has no positive values, and therefore can not be log-scaled."
```
Rest of the tests passing normally locally.

**Comment by dilawar** [comment]
@upibhalla @nishaann @hrani Reminder for review. This PR integrates more tests with Travis CI.

**Comment by dilawar** [comment]
@upibhalla @nishaann @hrani reminder on this PR.

**Comment by dilawar** [comment]
@upibhalla @nishaann @hrani reminder.

**Comment by hrani** [comment]
ok

**Review by hrani — APPROVED** [review]
ok

**Pull request merged**
